SELECT PS1.NOME COLABORADOR, CM.ID COMANDA, SV.DESCRICAO SERVICO,SV.VALOR VALOR FROM TB_COMANDA CM	
	JOIN TB_FORMA_PAGAMENTO FP ON CM.FORMA_PAGAMENTO_ID  = FP.ID
	JOIN TB_ITEM_COMANDA ICM ON ICM.COMANDA_ID = CM.ID
	JOIN TB_SERVICO SV ON ICM.SERVICO_ID = SV.ID
	JOIN TB_COLABORADOR CO1 ON ICM.COLABORADOR1_ID_COLABORADOR = CO1.ID_COLABORADOR
	JOIN TB_PESSOA PS1 ON CO1.ID_COLABORADOR = PS1.IDENT	
	WHERE PS1.IDENT = 1
	
	;
